class TraceidManager:

    def __init__(self, trace_id: str, history: set[str]):
        self._trace_id = trace_id
        self._history = history

    @property
    def trace_id(self) -> str:
        """Current testcase trace_id value."""
        pass

    def is_testsuite(self, trace_id: str | None) -> bool:
        """Returns True when `trace_id` was generated by testsuite."""
        pass

    def is_other_test(self, trace_id: str | None) -> bool:
        """Returns True when trace_id was generated by one of the previous testcases."""
        pass
